In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Telcom_Customer_Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.shape

(7043, 21)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [8]:
df["TotalCharges"] = df["TotalCharges"].str.strip()

In [10]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [11]:
df["TotalCharges"].dtype

dtype('float64')

In [14]:
df[df["TotalCharges"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [15]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [17]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [18]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [19]:
df["Contract"].value_counts()

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [20]:
df["InternetService"].value_counts()

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [21]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [22]:
df[["tenure", "MonthlyCharges", "TotalCharges"]].describe()

            tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7043.000000
mean     32.371149       64.761692   2279.734304
std      24.559481       30.090047   2266.794470
min       0.000000       18.250000      0.000000
25%       9.000000       35.500000    398.550000
50%      29.000000       70.350000   1394.550000
75%      55.000000       89.850000   3786.600000
max      72.000000      118.750000   8684.800000

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [24]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [25]:
df = df.rename(
    columns={
        "customerID":"CustomerID",
        "gender":"Gender",
        "tenure":"Tenure",
        
    }
)

In [26]:
df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   str
 1   Gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   Tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [28]:
churn_percentage = (df["Churn"].value_counts(normalize=True) * 100)

In [29]:
churn_percentage

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [30]:
contract_churn = pd.crosstab(df["Contract"], df["Churn"], normalize="index") * 100

In [31]:
contract_churn

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.730482  11.269518
Two year        97.168142   2.831858

In [32]:
internet_churn = pd.crosstab(df["InternetService"], df["Churn"], normalize="index") * 100

In [33]:
internet_churn

Churn                   No        Yes
InternetService
DSL              81.040892  18.959108
Fiber optic      58.107235  41.892765
No               92.595020   7.404980

In [34]:
payment_churn = pd.crosstab(df["PaymentMethod"], df["Churn"], normalize="index") * 100

In [35]:
payment_churn

Churn                             No        Yes
PaymentMethod
Bank transfer (automatic)  83.290155  16.709845
Credit card (automatic)    84.756899  15.243101
Electronic check           54.714588  45.285412
Mailed check               80.893300  19.106700

In [36]:
gender_churn = pd.crosstab(df["Gender"], df["Churn"], normalize="index") * 100

In [37]:
gender_churn

Churn          No        Yes
Gender
Female  73.079128  26.920872
Male    73.839662  26.160338

In [38]:
senior_churn = pd.crosstab(df["SeniorCitizen"], df["Churn"], normalize="index") * 100

In [39]:
senior_churn

Churn                 No        Yes
SeniorCitizen
0              76.393832  23.606168
1              58.318739  41.681261

In [40]:
partner_churn = pd.crosstab(df["Partner"], df["Churn"], normalize="index") * 100

In [41]:
partner_churn

Churn           No        Yes
Partner
No       67.042021  32.957979
Yes      80.335097  19.664903

In [42]:
dependents_churn = pd.crosstab(df["Dependents"], df["Churn"], normalize="index") * 100

In [43]:
dependents_churn

Churn              No        Yes
Dependents
No          68.720860  31.279140
Yes         84.549763  15.450237

In [44]:
phone_churn = pd.crosstab(df["PhoneService"], df["Churn"], normalize="index") * 100

In [45]:
phone_churn

Churn                No        Yes
PhoneService
No            75.073314  24.926686
Yes           73.290363  26.709637

In [46]:
multiple_churn = pd.crosstab(df["MultipleLines"], df["Churn"], normalize="index") * 100

In [47]:
multiple_churn

Churn                    No        Yes
MultipleLines
No                74.955752  25.044248
No phone service  75.073314  24.926686
Yes               71.390104  28.609896

In [48]:
security_churn = pd.crosstab(df["OnlineSecurity"], df["Churn"], normalize="index") * 100

In [49]:
security_churn

Churn                       No        Yes
OnlineSecurity
No                   58.233276  41.766724
No internet service  92.595020   7.404980
Yes                  85.388806  14.611194

In [50]:
onlinebackup_churn = pd.crosstab(df["OnlineBackup"], df["Churn"], normalize="index") * 100

In [51]:
onlinebackup_churn

Churn                       No        Yes
OnlineBackup
No                   60.071244  39.928756
No internet service  92.595020   7.404980
Yes                  78.468506  21.531494

In [52]:
deviceprotection_churn = pd.crosstab(df["DeviceProtection"], df["Churn"], normalize="index") * 100

In [53]:
deviceprotection_churn

Churn                       No        Yes
DeviceProtection
No                   60.872375  39.127625
No internet service  92.595020   7.404980
Yes                  77.497936  22.502064

In [54]:
techsupport_churn = pd.crosstab(df["TechSupport"], df["Churn"], normalize="index") * 100

In [55]:
techsupport_churn

Churn                       No        Yes
TechSupport
No                   58.364526  41.635474
No internet service  92.595020   7.404980
Yes                  84.833659  15.166341

In [56]:
streamingtv_churn = pd.crosstab(df["StreamingTV"], df["Churn"], normalize="index") * 100

In [57]:
streamingtv_churn

Churn                       No        Yes
StreamingTV
No                   66.476868  33.523132
No internet service  92.595020   7.404980
Yes                  69.929812  30.070188

In [58]:
streamingmovies_churn = pd.crosstab(df["StreamingMovies"], df["Churn"], normalize="index") * 100

In [59]:
streamingmovies_churn

Churn                       No        Yes
StreamingMovies
No                   66.319569  33.680431
No internet service  92.595020   7.404980
Yes                  70.058565  29.941435

In [60]:
paperlessbilling_churn = pd.crosstab(df["PaperlessBilling"], df["Churn"], normalize="index") * 100

In [61]:
paperlessbilling_churn

Churn                    No        Yes
PaperlessBilling
No                83.669916  16.330084
Yes               66.434908  33.565092

In [62]:
df.groupby("Churn")["Tenure"].mean()

Churn
No     37.569965
Yes    17.979133
Name: Tenure, dtype: float64

In [63]:
df.groupby("Churn")["MonthlyCharges"].mean()

Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [64]:
df.groupby("Churn")["TotalCharges"].mean()

Churn
No     2549.911442
Yes    1531.796094
Name: TotalCharges, dtype: float64

In [65]:
df["TenureGroup"] = pd.cut(df["Tenure"], bins=[0, 12, 24, 48, 72], labels=["0-12 months", "13-24 monthd", "25-48 months", "49-72 months" ])

In [67]:
df[["Tenure", "TenureGroup"]].head(10)

   Tenure   TenureGroup
0       1   0-12 months
1      34  25-48 months
2       2   0-12 months
3      45  25-48 months
4       2   0-12 months
5       8   0-12 months
6      22  13-24 monthd
7      10   0-12 months
8      28  25-48 months
9      62  49-72 months

In [68]:
tenuregroup_churn = pd.crosstab(df["TenureGroup"], df["Churn"], normalize="index") * 100

In [69]:
tenuregroup_churn

Churn                No        Yes
TenureGroup
0-12 months   52.321839  47.678161
13-24 monthd  71.289062  28.710938
25-48 months  79.611041  20.388959
49-72 months  90.486824   9.513176

In [70]:
tenure_contract_churn = pd.crosstab(df["TenureGroup"], df["Contract"], normalize="index") * 100

In [71]:
tenure_contract_churn

Contract      Month-to-month   One year   Two year
TenureGroup
0-12 months        91.678161   5.655172   2.666667
13-24 monthd       71.972656  19.238281   8.789062
25-48 months       50.313676  32.496863  17.189460
49-72 months       15.274676  28.316213  56.409111

In [75]:
internet_contract_churn = pd.crosstab([df["InternetService"], df["Contract"]], df["Churn"], normalize='index') * 100

In [76]:
internet_contract_churn

Churn                                  No        Yes
InternetService Contract
DSL             Month-to-month  67.784137  32.215863
                One year        90.701754   9.298246
                Two year        98.089172   1.910828
Fiber optic     Month-to-month  45.394737  54.605263
                One year        80.705009  19.294991
                Two year        92.773893   7.226107
No              Month-to-month  81.106870  18.893130
                One year        97.527473   2.472527
                Two year        99.216301   0.783699

In [77]:
payment_contract_churn = pd.crosstab([df["PaymentMethod"], df["Contract"]], df["Churn"], normalize="index") * 100

In [78]:
payment_contract_churn

Churn                                            No        Yes
PaymentMethod             Contract
Bank transfer (automatic) Month-to-month  65.874363  34.125637
                          One year        90.281330   9.718670
                          Two year        96.631206   3.368794
Credit card (automatic)   Month-to-month  67.219153  32.780847
                          One year        89.698492  10.301508
                          Two year        97.762478   2.237522
Electronic check          Month-to-month  46.270270  53.729730
                          One year        81.556196  18.443804
                          Two year        92.261905   7.738095
Mailed check              Month-to-month  68.421053  31.578947
                          One year        93.175074   6.824926
                          Two year        99.214660   0.785340

In [79]:
security_contract_churn = pd.crosstab([df["OnlineSecurity"], df["Contract"]], df["Churn"], normalize="index") * 100

In [80]:
security_contract_churn

Churn                                      No        Yes
OnlineSecurity      Contract
No                  Month-to-month  48.954770  51.045230
                    One year        82.585278  17.414722
                    Two year        93.225806   6.774194
No internet service Month-to-month  81.106870  18.893130
                    One year        97.527473   2.472527
                    Two year        99.216301   0.783699
Yes                 Month-to-month  70.416667  29.583333
                    One year        89.130435  10.869565
                    Two year        97.054886   2.945114

In [81]:
internet_security_churn = pd.crosstab([df["InternetService"], df["OnlineSecurity"]], df["Churn"], normalize="index") * 100

In [82]:
internet_security_churn

Churn                                       No        Yes
InternetService OnlineSecurity
DSL             No                   72.038678  27.961322
                Yes                  90.508475   9.491525
Fiber optic     No                   50.642446  49.357554
                Yes                  78.188319  21.811681
No              No internet service  92.595020   7.404980

In [83]:
df["Monthlychargesgroup"] = pd.cut(df["MonthlyCharges"], bins=[0, 50, 80, 120], labels=["Low","Medium","High"])

In [84]:
df[["MonthlyCharges", "Monthlychargesgroup"]].head(10)

   MonthlyCharges Monthlychargesgroup
0           29.85                 Low
1           56.95              Medium
2           53.85              Medium
3           42.30                 Low
4           70.70              Medium
5           99.65                High
6           89.10                High
7           29.75                 Low
8          104.80                High
9           56.15              Medium

In [85]:
monthlycharges_contract = pd.crosstab([df["Monthlychargesgroup"], df["Contract"]], df["Churn"], normalize="index") * 100

In [86]:
monthlycharges_contract

Churn                                      No        Yes
Monthlychargesgroup Contract
Low                 Month-to-month  69.928187  30.071813
                    One year        95.983087   4.016913
                    Two year        99.016854   0.983146
Medium              Month-to-month  57.098765  42.901235
                    One year        91.264368   8.735632
                    Two year        97.694524   2.305476
High                Month-to-month  47.849829  52.150171
                    One year        80.707965  19.292035
                    Two year        94.811321   5.188679

In [92]:
high_risk = df[
    (df["Tenure"] <= 12) &
    (df["Contract"] == "Month-to-month") &
    (df["InternetService"] == "Fiber optic") &
    (df["OnlineSecurity"] == "No") &
    (df["PaymentMethod"] == "Electronic check")
]

In [93]:
high_risk

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TenureGroup,Monthlychargesgroup
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-12 months,Medium
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,0-12 months,High
36,6047-YHPVI,Male,0,No,No,5,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,69.70,316.90,Yes,0-12 months,Medium
47,7760-OYPDY,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,No,Month-to-month,Yes,Electronic check,80.65,144.15,Yes,0-12 months,High
64,5698-BQJOH,Female,0,No,No,9,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,No,Electronic check,94.40,857.25,Yes,0-12 months,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6936,7693-LCKZL,Male,0,Yes,Yes,5,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,80.15,385.00,Yes,0-12 months,High
6957,3914-FDRHP,Male,0,No,No,9,Yes,No,Fiber optic,No,...,Yes,No,Month-to-month,No,Electronic check,86.25,770.50,No,0-12 months,High
6970,8083-YTZES,Male,0,No,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,74.35,265.35,Yes,0-12 months,Medium
7010,0723-DRCLG,Female,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,74.45,74.45,Yes,0-12 months,Medium
7032,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes,0-12 months,Medium

In [96]:
high_risk["Churn"].value_counts(normalize=True) * 100

Churn
Yes    73.070326
No     26.929674
Name: proportion, dtype: float64

In [95]:
high_risk["Churn"].value_counts()

Churn
Yes    426
No     157
Name: count, dtype: int64

In [100]:
strong_indicators = {
    "Factors": [
        "Contract", "InternetService", "PaymentMethod", "Tenure", "OnlineSecurity", "TechSupport", "MonthlyCharges"],
    "Findings": [
        "Month to month customers have high churn",
        "Fiber optic customers have high churn",
        "Electronic check users have high churn",
        "New customers have high churn",
        "Customers without online security have high churn",
        "Customers without tech support have high churn",
        "Higher monthly charges are associated with higher churn"
    ]    
}

In [101]:
strong_indicators = pd.DataFrame(strong_indicators)

In [102]:
strong_indicators

           Factors                                           Findings
0         Contract           Month to month customers have high churn
1  InternetService              Fiber optic customers have high churn
2    PaymentMethod             Electronic check users have high churn
3           Tenure                      New customers have high churn
4   OnlineSecurity  Customers without online security have high churn
5      TechSupport     Customers without tech support have high churn
6   MonthlyCharges  Higher monthly charges are associated with hig...

In [106]:
df.to_csv("Telecom_churn_cleaned.csv", index=False)